### ISSUE TITLE
modal using alpine.js

### ISSUE THREAD

**Issue by Santa116** [Santa116/Upwork-messengerUI#2]

**Comment by dev0614** [comment]
<div x-data="{ open: false }" @click.away="open = false" class="relative">
                        <button @click="open = !open">
                            <i class="bx bx-slider-alt text-green-600"></i>
                        </button>

                        <div x-show="open" x-transition:enter="transition ease-out duration-200"
                            x-transition:enter-start="transform opacity-0 scale-95"
                            x-transition:enter-end="transform opacity-100 scale-100"
                            x-transition:leave="transition ease-in duration-75"
                            x-transition:leave-start="transform opacity-100 scale-100"
                            x-transition:leave-end="transform opacity-0 scale-95"
                            class="absolute z-10 left-1/2 transform -translate-x-1/2 mt-2 w-52 h-64 overflow-y-scroll bg-white shadow-xl rounded divide-y divide-gray-100"
                            @click="open = false">
                            <ul class="py-1 text-gray-700">
                                <li class="block text-[16px] px-4 py-2 text-gray-400">Filter conversation by</li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-check text-green-600 mr-2"></i>All</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-envelope mr-2"></i>Unread</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-star mr-2"></i>Favorites</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-briefcase mr-2"></i>Interviews</a>
                                </li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="fa fa-paper-plane mr-2"></i>Contracts</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-paperclip mr-2"></i>Fixed-price
                                        contract</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-stopwatch mr-2"></i>Hourly
                                        contract</a></li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-hide mr-2"></i>Hidden &
                                        Achived</a></li>
                                <li class="block text-[16px] px-4 py-2 text-gray-400">Filter messagesby</li>
                                <li><a href="#" class="block text-[16px] px-4 py-2 hover:bg-gray-100"><i
                                            class="bx bx-star mr-2"></i>Favorites
                                        messages</a></li>
                            </ul>
                        </div>
                    </div>

**Comment by Santa116** [comment]
thank you.

**Comment by dev0614** [comment]
You are welcome!
